### PR TITLE
remove $fuck (only 1 pull)

### PR DESCRIPTION
**Pull request by ToggledX**
It removes $fuck directly, feel free to use it or not. If you think $fuck will make the bot want to be in many servers then it's your choice

### CODE REVIEW

**Comment by ToggledX** [comment]
oop wrong commits

**Comment by diceflip** [comment]
lol never seen the commit until now
changing github code doesnt remove the command in the bot.

**Comment by diceflip** [comment]
Its a good command ig
and this bot is not meant for servers, its for developers who want to learn to make bots.

**Comment by ToggledX** [comment]
Okay sorry i was not on pc and i made them on GitHub editor its good to have a code to help people to code but python is not really the thing that should be on the code. On 1 or 2 updates it will get outdated

**Comment by diceflip** [comment]
my bots made last year never got outdated, it wont happen since this bot uses basic code and an api.

**Comment by ToggledX** [comment]
dpy is outdated

**Pull request closed without merging**
